[meta]
name = "Auto Enable PB Ghost"
author = "ar"
version = "0.4.3.2"
category = "Utilities"
siteid = 648

[script]
dependencies = [ "MLHook", "NadeoServices" ]
optional_dependencies = [ "BetterReplaysFolder" ]
timeout = 0